
-- Importierte Rezepte aus app/data/ach_db.JSON
-- Generiert mit generate-seed.mjs

INSERT INTO source_types (source_type, stid) VALUES
  ('Magazin', 1),
  ('Buch', 2),
  ('Internet',3),
  ('Persönlich',4);

INSERT INTO recipes (id, title, description, servings, prep_time, cook_time, category) VALUES
  (3, 'Pürees', NULL, NULL, NULL, NULL, 'Beilagen'),
  (4, 'Suppe', NULL, NULL, NULL, NULL, 'Suppen'),
  (5, 'Schmorbraten', 'Fleisch', NULL, NULL, NULL, 'Hauptgerichte'),
  (6, 'Salate', 'Ausgefallene Dressings', NULL, NULL, NULL, 'Salate'),
  (7, 'Soßen', 'Saucen, Dressings', NULL, NULL, NULL, 'Beilagen'),
  (8, 'Grill-Spieße', 'Fleisch, Grillen', NULL, NULL, NULL, 'Hauptgerichte'),
  (9, 'Safran-Mandel-Suppe', 'mit Chili-Croutons, Vegetarisch', NULL, NULL, NULL, 'Suppen'),
  (10, 'Tomatensuppe mit Zimt und Garnelen', 'Fisch', NULL, NULL, NULL, 'Suppen'),
  (11, 'Lauchpuffer', 'Pfanne, vegetarisch', NULL, NULL, NULL, 'Hauptgerichte'),
  (12, 'Entenbrust mit Portwein-Pflaumen-Sauce', 'Fleisch, Ente, Grillen', NULL, NULL, NULL, 'Hauptgerichte'),
  (13, 'Rote Paprikaschaumsuppe mit Ziegenkäse-Ravioli', 'vegetarisch', NULL, NULL, NULL, 'Suppen'),
  (14, 'Steaks', 'Grillen, Fleisch', NULL, NULL, NULL, 'Hauptgerichte'),
  (15, 'Rouille', 'Feinschmecker-Version, Soße, Sauce', NULL, NULL, NULL, 'Beilagen'),
  (16, 'Rote Bete Sauce', 'Soße, Sauce', NULL, NULL, NULL, 'Beilagen'),
  (17, 'Salze', NULL, NULL, NULL, NULL, 'Gewürze'),
  (18, 'Soßen', 'Grillen, Sauce, Soße', NULL, NULL, NULL, 'Beilagen'),
  (19, 'Tomaten aus dem Ofen', 'Vegetarisch', NULL, NULL, NULL, 'Beilagen'),
  (20, 'Salate', 'Fisch, Fleisch', NULL, NULL, NULL, 'Salate'),
  (21, 'Ravioli', 'Vegetarisch, Fleisch, Nudeln', NULL, NULL, NULL, 'Hauptgerichte'),
  (22, 'Honig', 'Fleisch', NULL, NULL, NULL, 'Hauptgerichte'),
  (23, 'Kohl', 'Vegetarisch, Fleisch', NULL, NULL, NULL, 'Hauptgerichte'),
  (24, 'Lachs gebeizt', 'Fisch', NULL, NULL, NULL, 'Hauptgerichte'),
  (25, 'Steaks', 'Fleisch, Grillen', NULL, NULL, NULL, 'Hauptgerichte'),
  (26, 'Knödel', 'Vegetarisch', NULL, NULL, NULL, 'Beilagen'),
  (27, 'Schwein', 'Fleisch', NULL, NULL, NULL, 'Hauptgerichte'),
  (28, 'Grillen & Rubs', 'US-Style mit Rauch - indirektes Grillen, Fleisch', NULL, NULL, NULL, 'Hauptgerichte'),
  (29, 'Gemüse-Carpaccio', 'Vegetarisch, Fleisch', NULL, NULL, NULL, 'Vorspeisen und Zwischenmahlzeiten'),
  (30, 'Roast-Beef', 'Ausführliche Anleitung, Fleisch, Rind', NULL, NULL, NULL, 'Hauptgerichte'),
  (31, 'Desserts', 'Nachtisch mit Alkohol', NULL, NULL, NULL, 'Nachspeisen'),
  (32, 'Fonds', NULL, NULL, NULL, NULL, 'Beilagen'),
  (33, 'Lamm', 'Fleisch', NULL, NULL, NULL, 'Hauptgerichte'),
  (34, 'Bohnen', 'Vegetarisch, Fleisch', NULL, NULL, NULL, 'Beilagen'),
  (35, 'Grillen', 'Fleisch', NULL, NULL, NULL, 'Hauptgerichte'),
  (36, 'Soßen', 'Zu Fleisch und Fisch, Saucen', NULL, NULL, NULL, 'Beilagen'),
  (37, 'Forelle Müllerin-Art', 'Filets am Spieß, Fisch', NULL, NULL, NULL, 'Vorspeisen und Zwischenmahlzeiten'),
  (38, 'Böfflamott', 'Rinderschulter, Fleisch', NULL, NULL, NULL, 'Hauptgerichte'),
  (39, 'Krustenbraten vom Spanferkel', 'Rollbraten, Schweinerücken und -bauch im Ganzen, Fleisch', NULL, NULL, NULL, 'Hauptgerichte'),
  (40, 'Rotkohlsalat mit geräucherter Entenbrust', 'Fleisch', NULL, NULL, NULL, 'Salate'),
  (41, 'Rahmwirsing mit Wildhasenrücken im Speckmantel', 'Fleisch', NULL, NULL, NULL, 'Hauptgerichte'),
  (42, 'Spiegelei auf Rahmspinat', 'Vegetarisch', NULL, NULL, NULL, 'Hauptgerichte'),
  (43, 'Hähnchenkeulen mit Calvados', 'Französisch, Fleisch', NULL, NULL, NULL, 'Hauptgerichte'),
  (44, 'Birnen im Schlafrock', 'Französisch', NULL, NULL, NULL, 'Nachspeisen'),
  (45, 'Kaninchensalat nach Meisterart', 'Französisch, Fleisch', NULL, NULL, NULL, 'Salate'),
  (46, 'Raito', 'Französisch, Soße, Sauce, Passt zu Fisch', NULL, NULL, NULL, 'Beilagen'),
  (47, 'Geschmorte Lammkeule', 'Französisch, Fleisch', NULL, NULL, NULL, 'Hauptgerichte'),
  (48, 'Schollenfilets mit Spinat und Tomaten', 'Nordisch, Fisch', NULL, NULL, NULL, 'Hauptgerichte'),
  (49, 'Eingelegte Bratheringe', 'Nordisch, Fisch', NULL, NULL, NULL, 'Hauptgerichte'),
  (50, 'Lamm-Eintopf', 'Nordisch, Fleisch', NULL, NULL, NULL, 'Hauptgerichte'),
  (51, 'Schweinebraten aus dem Ofen', 'Nordisch, Fleisch', NULL, NULL, NULL, 'Hauptgerichte'),
  (52, 'Steinbeißerfilet auf Spitzkohl', 'Fisch', NULL, NULL, NULL, 'Hauptgerichte'),
  (53, 'Knusperrolle mit Forelle und Kaninchen-Rillets', 'Fisch, Fleisch', NULL, NULL, NULL, 'Hauptgerichte'),
  (54, 'Seeteufel-Tournedos imSpeckmantel', 'Fisch', NULL, NULL, NULL, 'Hauptgerichte'),
  (55, 'Tomatensalat mit mariniertem Schafskäse', 'Vegetarisch', NULL, NULL, NULL, 'Salate'),
  (56, 'Avocado-Aufstrich mit Wasabi', 'Vegetarisch', NULL, NULL, NULL, 'Beilagen'),
  (57, 'Lammpilaw mit Kreuzkümmel', 'Fleisch', NULL, NULL, NULL, 'Hauptgerichte'),
  (58, 'Gemüsestrudel mit Thunfischsauce', 'Vegetarisch, Fisch', NULL, NULL, NULL, 'Hauptgerichte'),
  (59, 'Mit Kümmel gebratene Lotte', 'Fisch', NULL, NULL, NULL, 'Hauptgerichte'),
  (60, 'Rotes Wallercurry', 'mit Weißkraut und Cocktailtomaten, Fisch', NULL, NULL, NULL, 'Hauptgerichte'),
  (61, 'Schweindemedaillons', 'aus dem Gewürzsud mit Wasabi-Pesto, Pochiert, Fleisch', NULL, NULL, NULL, 'Beilagen'),
  (62, 'Gewürzkrustenbraten auf Schmorgemüse', 'Fleisch', NULL, NULL, NULL, 'Hauptgerichte'),
  (63, 'Geschmortes Kaninchen', 'Ligurien, Fleisch', NULL, NULL, NULL, 'Hauptgerichte'),
  (64, 'Risotto', 'Lombardei, alla milanese, mit Spargel, mit Geflügelleber', NULL, NULL, NULL, 'Beilagen'),
  (65, 'Geschmorte Kalbshaxe', 'Lombardei, Fleisch', NULL, NULL, NULL, 'Hauptgerichte'),
  (66, 'Kalbsschnitzel mit Zitronensauce', 'Lombardei, Fleisch', NULL, NULL, NULL, 'Hauptgerichte'),
  (67, 'Vitello tonnato', 'Piemont, Kalb, Fleisch', NULL, NULL, NULL, 'Vorspeisen und Zwischenmahlzeiten'),
  (68, 'Frischer Pilzsalat', 'Aostatal', NULL, NULL, NULL, 'Beilagen'),
  (69, 'Weiße und grüne Bandnudeln mit Sahne-Pilzsauce', 'Toskana, Pasta, vegetarisch', NULL, NULL, NULL, 'Hauptgerichte'),
  (70, 'Gebratene Knoblauchpilze', 'Toskana, vegetarisch', NULL, NULL, NULL, 'Vorspeisen und Zwischenmahlzeiten'),
  (71, 'Bandnudeln mit Hühnerlebersauce', 'Latium, Fleisch', NULL, NULL, NULL, 'Vorspeisen und Zwischenmahlzeiten'),
  (72, 'Erbsen mit Schinken', 'Latium, Fleisch', NULL, NULL, NULL, 'Beilagen'),
  (73, 'Lammgulasch mit Zitronensauce', 'Abruzzen, Fleisch', NULL, NULL, NULL, 'Hauptgerichte'),
  (74, 'Makkaroni mit neapolitanischer Fleischsauce', 'Kampaninen, Fleisch, Pasta, Nudeln', NULL, NULL, NULL, 'Hauptgerichte'),
  (75, 'Auberginenauflauf', 'Kampanien, vegetarisch', NULL, NULL, NULL, 'Hauptgerichte'),
  (76, 'Pochiertes junges Gemüse mit Kapernmayonaise', 'vegetarisch', NULL, NULL, NULL, 'Beilagen'),
  (77, 'Rote Bete mit Joghurt und Zitronenrelish', 'vegetarisch', NULL, NULL, NULL, NULL),
  (78, 'Zucchini-Haselnuss-Salat', 'vegetarisch', NULL, NULL, NULL, 'Salate'),
  (79, 'Marinierte Paprikaschoten und Pecorino', 'vegetarisch', NULL, NULL, NULL, 'Salate'),
  (80, 'Brokkoli-Gorgonzola-Pie', 'vegetarisch', NULL, NULL, NULL, 'Hauptgerichte'),
  (81, 'Rauchige Frittata', 'Blumenkohl, Käse, vegetarisch', NULL, NULL, NULL, 'Hauptgerichte'),
  (82, 'Marinierter Büffelmozzarella mit Tomaten', 'Käse, vegetarisch', NULL, NULL, NULL, 'Beilagen'),
  (83, 'Spiegeleier mit Joghurt und Chili', 'Rucola, Jogurt, vegetarisch', NULL, NULL, NULL, 'Hauptgerichte'),
  (84, 'Gurkensalat mit Knoblauch und Ingwer', 'vegetarisch', NULL, NULL, NULL, 'Salate'),
  (85, 'Gemischte Bohnen mit Liebstöckel und aromatischen Gewürzen', 'vegetarisch', NULL, NULL, NULL, 'Beilagen'),
  (86, 'Graupen-Granatapfel-Salat', 'vegetarisch', NULL, NULL, NULL, 'Salate'),
  (87, 'Kardamonreis mit pochiertem Ei und Joghurt', 'vegetarisch', NULL, NULL, NULL, NULL),
  (88, 'Zitronen-Ziegenkäse-Ravioli', 'Pasta, Nudeln, vegetarisch', NULL, NULL, NULL, 'Hauptgerichte'),
  (89, 'Safrantagiatelle mit Gewürzbutter', 'Pasta, Nudeln, vegetarisch', NULL, NULL, NULL, NULL),
  (90, 'Rotweinburger mit Rosmarin-Focaccia', 'Rind, Fleisch, Grillen', NULL, NULL, NULL, 'Hauptgerichte'),
  (91, 'Rib-Eye-Steaks mit Espresso-Chili-Kruste', 'Rind, Fleisch, Grillen', NULL, NULL, NULL, 'Beilagen'),
  (92, 'Rinderrippen mit Barbacoa-Sauce', 'Rind, Fleisch, Grillen', NULL, NULL, NULL, 'Hauptgerichte'),
  (93, 'Lammkeule mit marokkanischen Gewürzen', 'Fleisch, Lamm, Grillen', NULL, NULL, NULL, 'Hauptgerichte'),
  (94, 'In Cidre eingelegte Lendensteaks', 'Fleisch, Schwein, Grillen', NULL, NULL, NULL, 'Hauptgerichte'),
  (95, 'Sandwich mit Schweinesteak, Paprika und Käse', 'Fleisch, Schwein, Grillen', NULL, NULL, NULL, 'Hauptgerichte'),
  (96, 'Schweinemedallions mit asiatischer Schwarze-Bohnen-Sauce', 'Fleisch, Schwein, Grillen', NULL, NULL, NULL, 'Hauptgerichte'),
  (97, 'Dicke Rippe mit Tamarindenglasur', 'Fleisch, Schwein, Grillen', NULL, NULL, NULL, 'Hauptgerichte'),
  (98, 'Hähnchenbrust mit Zitrone und Oregano', 'Fleisch, Huhn, Grillen', NULL, NULL, NULL, 'Hauptgerichte'),
  (99, 'In Whisky, Soja und Honig mariniertes Stubenküken', 'Fleisch, Huhn, Grillen', NULL, NULL, NULL, 'Hauptgerichte'),
  (100, 'Muskathähnchen unter der Gusseisenpfanne', 'Fleisch, Huhn, Grillen', NULL, NULL, NULL, 'Hauptgerichte'),
  (101, 'Schwertfisch mit Gemüse-Escabeche', 'Fisch, Grillen', NULL, NULL, NULL, 'Hauptgerichte'),
  (102, 'Lachs mit Curry-Kokos-Sauce', 'Fisch, Grillen', NULL, NULL, NULL, 'Hauptgerichte'),
  (103, 'Ganzer Felsenbarsch mit marokkanischer Marinade', 'Fisch, Grillen', NULL, NULL, NULL, 'Hauptgerichte'),
  (104, 'Salat mit Gegrillter Paprika, Zwiebeln und Feta', 'Vegetarisch, Grillen, Salat', NULL, NULL, NULL, 'Salate'),
  (105, 'Möhren mit Oragenglasur', 'Vegetarisch, Grillen', NULL, NULL, NULL, 'Beilagen'),
  (106, 'Gegrillter Fladen mit Dreierlei Aufstrich', 'Vegetarisch, Grillen', NULL, NULL, NULL, 'Beilagen'),
  (107, 'Rote-Bete-Suppe mit Walnuss-Pesto & Engelshaar', 'Vegetarisch', NULL, NULL, NULL, 'Suppen'),
  (108, 'Pilz-Consomé mit Trüffel-Kartoffel-Ravioli', 'vegetarisch', NULL, NULL, NULL, 'Suppen'),
  (109, 'Scharfe Entensuppe mit Eiernudeln und Sprossen', NULL, NULL, NULL, NULL, 'Suppen'),
  (110, 'Kohlrabi-Birnen-Suppe mit Geflügelleber', NULL, NULL, NULL, NULL, 'Suppen'),
  (111, 'Geflügel-Consomé mit geröstetem Knoblauch', NULL, NULL, NULL, NULL, 'Suppen'),
  (112, 'Wurzelgemüse-Eintopf mit gesottener Rinderbrust', NULL, NULL, NULL, NULL, 'Suppen'),
  (113, 'Sauerkrautsuppe mit Merrettich-Schmand', 'Kartoffeln, Speck', NULL, NULL, NULL, 'Suppen'),
  (114, 'Erdbeer-Paprika-Tomaten-Cocktail', 'Orangensaft, Basilikum, vegetarisch', NULL, NULL, NULL, 'Getränke'),
  (115, 'Lammschulter mit Peperoni & Zwiebeln', 'Braten', NULL, NULL, NULL, 'Hauptgerichte'),
  (116, 'Schweinshaxe asia-style', 'Braten', NULL, NULL, NULL, 'Hauptgerichte'),
  (117, 'Ceviche von Garnele & Dorade', 'Fisch', NULL, NULL, NULL, 'Hauptgerichte'),
  (118, 'Scharfe Brösel', 'Fleisch, Wurst', NULL, NULL, NULL, 'Gewürze'),
  (119, 'Schweinshaxe aus dem Rohr', 'Fleisch', NULL, NULL, NULL, 'Hauptgerichte'),
  (120, 'Schmorbraten Wild', 'Fleisch', NULL, NULL, NULL, 'Hauptgerichte'),
  (121, 'Brot', NULL, NULL, NULL, NULL, 'Brote'),
  (122, 'Fondue', 'Fleisch', NULL, NULL, NULL, 'Hauptgerichte'),
  (123, 'Bierzander auf Wirsing-Gemüse', 'Fisch', NULL, NULL, NULL, NULL),
  (124, 'Ottolenghis Rezept: Langsames Lamm', '6 Stunden schmoren, Für Starkoch Yotam Ottolenghi geht kaum etwas so gut zusammen wie Fleisch und Früchte. Heute schiebt er eine Lammschulter mit Pflaumen und Mandeln in den Ofen - und 25 Knoblauchzehen.', NULL, NULL, NULL, NULL),
  (125, 'Fischfilet mit Orangen-Erdnusskruste', '1., Fischfilets mit Zitronensaft beträufeln. Mit Salz und Pfeffer würzen. Von der Hälfte der Orangen Schale fein abreiben. Von den restlichen Orangen Schale in Zesten abziehen. Orangen auspressen. Erdnüsse in einem Cutter fein hacken. Orangenschale, die Hälfte des Safts, Wasser, wenig Olivenöl und wenig Honig dazumischen. Mit Pfeffer und einigen abgezupften Thymianblättchen aromatisieren., 2., Backofen auf 200 °C vorheizen. Restliches Öl in eine ofenfeste Form giessen. Filets in die Form legen. Erdnussmasse darauf verteilen und gut andrücken. Form in die untere Hälfte des Ofens schieben. Den Fisch 15-20 Minuten backen, bis die Kruste goldbraun ist., 3., Inzwischen Orangenzesten, restlichen Orangensaft, Wein, einige Thymianzweige und restlichen Honig in einer kleinen Pfanne aufkochen. Maisstärke in wenig Wasser auflösen. In die Sauce einrühren. Sauce kurz kochen lassen. Mit Salz und Pfeffer abschmecken., 4., Fischfilets auf der Sauce anrichten. Mit frischen Thymianzweigen servieren.', NULL, NULL, NULL, 'Hauptgerichte'),
  (126, 'Secreto Iberico - Geheimes Filet', 'Großartig!!!, Schwein', NULL, NULL, NULL, 'Hauptgerichte'),
  (127, 'Putenschnitzel Pomme', 'Fleisch', NULL, NULL, NULL, NULL),
  (128, 'Kaninchen Échalote', 'Fleisch', NULL, NULL, NULL, NULL),
  (129, 'Calvados-Hähnchen in Cidre-Soße', 'Fleisch', NULL, NULL, NULL, NULL),
  (130, 'Schweinebraten Nantosuelta', 'Fleisch', NULL, NULL, NULL, NULL),
  (131, 'Bretonisches Kaninchenragout', 'Fleisch', NULL, NULL, NULL, NULL),
  (132, 'Lammkeule Ail', 'Fleisch', NULL, NULL, NULL, NULL),
  (133, 'Boeuf à la mode', 'Fleisch', NULL, NULL, NULL, NULL),
  (134, 'Entenbrust in Cidre-Butter', 'Fleisch', NULL, NULL, NULL, NULL),
  (135, 'Lamm mit Kreuzkümmel und Koriander', 'Chinesisch, Fleisch', NULL, NULL, NULL, 'Hauptgerichte'),
  (136, 'Pulled Pork', 'Fleisch, Schwein', NULL, NULL, NULL, NULL);

INSERT INTO sources (recipe_id, source, source_detail, note, source_type_id) VALUES
  (3, 'Beef 5', 'S. 156', NULL, 1),
  (4, 'Beef 7', 'S. 54 ff', NULL, 1),
  (5, 'Beef 8', 'S. 124 ff', NULL, 1),
  (6, 'Beef 10', 'S. 70 ff', NULL, 1),
  (7, 'Beef 10', 'S. 90 ff', NULL, 1),
  (8, 'Beef 11', 'S. 34 ff', 'Satés: Kokosraspeln vorher einweichen', 1),
  (9, 'Schuhbecks Gewürze', 'S. 182', NULL, 2),
  (10, 'Schuhbecks Gewürze', 'S. 194', NULL, 2),
  (11, 'Genussvoll vegetarisch', 'S. 36', NULL, 2),
  (12, 'Webers Grillbibel', 'S. 141', NULL, 2),
  (13, 'Lust auf Genuss 12/13', 'S. 35', NULL, 1),
  (14, 'Beef 1', 'S. 37ff', NULL, 1),
  (15, 'Beef 1', 'S. 37ff. 67', NULL, 1),
  (16, 'Beef 1', 'S. 71', NULL, 1),
  (17, 'Beef 1', 'S. 140ff', NULL, 1),
  (18, 'Beef 2', 'S. 122ff', NULL, 1),
  (19, 'Beef 2', 'S. 153', NULL, 1),
  (20, 'Beef 3', 'S. 44ff', NULL, 1),
  (21, 'Beef 3', 'S. 78ff', NULL, 1),
  (22, 'Beef 3', 'S. 100ff', NULL, 1),
  (23, 'Beef 4', 'S. 50 ff', NULL, 1),
  (24, 'Beef 5', 'S. 84 ff', NULL, 1),
  (25, 'Beef 7', 'S. 37 ff', NULL, 1),
  (26, 'Beef 8', 'S. 60 ff', NULL, 1),
  (27, 'Beef 9', 'S. 32 ff', NULL, 1),
  (28, 'Beef 10', 'S. 34 ff', NULL, 1),
  (29, 'Beef 10', 'S. 124 ff', NULL, 1),
  (30, 'Beef 11', 'S. 122 ff', NULL, 1),
  (31, 'Beef 12', 'S. 122 ff', NULL, 1),
  (32, 'Beef 13', 'S. 148', NULL, 1),
  (33, 'Beef 14', 'S. 36 ff', NULL, 1),
  (34, 'Beef 14', 'S. 50 ff', NULL, 1),
  (35, 'Beef 14', 'S. 115 ff', NULL, 1),
  (36, 'Beef 15', 'S. 130 ff', NULL, 1),
  (37, 'Lust auf Genuss 3/11', 'S. 32', NULL, 1),
  (38, 'Lust auf Genuss 3/11', 'S. 46', NULL, 1),
  (39, 'Lust auf Genuss 3/11', 'S. 48', NULL, 1),
  (40, 'Lust auf Genuss 3/11', 'S. 54', NULL, 1),
  (41, 'Lust auf Genuss 3/11', 'S. 54', NULL, 1),
  (42, 'Lust auf Genuss 3/11', 'S. 62', NULL, 1),
  (43, 'Lust auf Genuss 7/11', 'S. 33', NULL, 1),
  (44, 'Lust auf Genuss 7/11', 'S. 36', NULL, 1),
  (45, 'Lust auf Genuss 7/11', 'S. 56', NULL, 1),
  (46, 'Lust auf Genuss 7/11', 'S. 72', NULL, 1),
  (47, 'Lust auf Genuss 7/11', 'S. 74', NULL, 1),
  (48, 'Lust auf Genuss 6/10', 'S. 22', NULL, 1),
  (49, 'Lust auf Genuss 6/10', 'S. 43', NULL, 1),
  (50, 'Lust auf Genuss 6/10', 'S. 43', NULL, 1),
  (51, 'Lust auf Genuss 6/10', 'S. 66', NULL, 1),
  (52, 'Lust auf Genuss 1/13', 'S. 41', NULL, 1),
  (53, 'Lust auf Genuss 1/13', 'S. 80', NULL, 1),
  (54, 'Lust auf Genuss 1/13', 'S. 81', NULL, 1),
  (55, 'Schuhbecks Gewürze', 'S. 157', NULL, 2),
  (56, 'Schuhbecks Gewürze', 'S. 165', NULL, 2),
  (57, 'Schuhbecks Gewürze', 'S. 220', NULL, 2),
  (58, 'Schuhbecks Gewürze', 'S. 242', NULL, 2),
  (59, 'Schuhbecks Gewürze', 'S. 260', NULL, 2),
  (60, 'Schuhbecks Gewürze', 'S. 264', NULL, 2),
  (61, 'Schuhbecks Gewürze', 'S. 278', NULL, 2),
  (62, 'Schuhbecks Gewürze', 'S. 282', NULL, 2),
  (63, 'Echte italienische Küche', 'S. 35', NULL, 2),
  (64, 'Echte italienische Küche', 'S. 57 ff', NULL, 2),
  (65, 'Echte italienische Küche', 'S. 66', NULL, 2),
  (66, 'Echte italienische Küche', 'S. 70', NULL, 2),
  (67, 'Echte italienische Küche', 'S. 99', NULL, 2),
  (68, 'Echte italienische Küche', 'S. 117', NULL, 2),
  (69, 'Echte italienische Küche', 'S. 139', NULL, 2),
  (70, 'Echte italienische Küche', 'S. 157', NULL, 2),
  (71, 'Echte italienische Küche', 'S. 181', NULL, 2),
  (72, 'Echte italienische Küche', 'S. 196', NULL, 2),
  (73, 'Echte italienische Küche', 'S. 226', NULL, 2),
  (74, 'Echte italienische Küche', 'S. 252', NULL, 2),
  (75, 'Echte italienische Küche', 'S. 262', NULL, 2),
  (76, 'Genussvoll vegetarisch', 'S. 12', NULL, 2),
  (77, 'Genussvoll vegetarisch', 'S. 19', NULL, 2),
  (78, 'Genussvoll vegetarisch', 'S. 70', NULL, 2),
  (79, 'Genussvoll vegetarisch', 'S. 82', NULL, 2),
  (80, 'Genussvoll vegetarisch', 'S. 92', NULL, 2),
  (81, 'Genussvoll vegetarisch', 'S. 96', NULL, 2),
  (82, 'Genussvoll vegetarisch', 'S. 126', NULL, 2),
  (83, 'Genussvoll vegetarisch', 'S. 140', NULL, 2),
  (84, 'Genussvoll vegetarisch', 'S. 166', NULL, 2),
  (85, 'Genussvoll vegetarisch', 'S. 192', NULL, 2),
  (86, 'Genussvoll vegetarisch', 'S. 238', NULL, 2),
  (87, 'Genussvoll vegetarisch', 'S. 240', NULL, 2),
  (88, 'Genussvoll vegetarisch', 'S. 250', 'Soße dazuerfinden', 2),
  (89, 'Genussvoll vegetarisch', 'S. 260', NULL, 2),
  (90, 'Webers Grillbibel', 'S. 36', NULL, 2),
  (91, 'Webers Grillbibel', 'S. 53', NULL, 2),
  (92, 'Webers Grillbibel', 'S. 84', NULL, 2),
  (93, 'Webers Grillbibel', 'S. 86', NULL, 2),
  (94, 'Webers Grillbibel', 'S. 101', NULL, 2),
  (95, 'Webers Grillbibel', 'S. 104', NULL, 2),
  (96, 'Webers Grillbibel', 'S. 108', NULL, 2),
  (97, 'Webers Grillbibel', 'S. 130', NULL, 2),
  (98, 'Webers Grillbibel', 'S. 138', NULL, 2),
  (99, 'Webers Grillbibel', 'S. 158', NULL, 2),
  (100, 'Webers Grillbibel', 'S. 167', NULL, 2),
  (101, 'Webers Grillbibel', 'S. 213', NULL, 2),
  (102, 'Webers Grillbibel', 'S. 202', NULL, 2),
  (103, 'Webers Grillbibel', 'S. 219', NULL, 2),
  (104, 'Webers Grillbibel', 'S. 241', NULL, 2),
  (105, 'Webers Grillbibel', 'S. 251', NULL, 2),
  (106, 'Webers Grillbibel', 'S. 262 f', NULL, 2),
  (107, 'Lust auf Genuss 12/13', 'S. 28', NULL, 1),
  (108, 'Lust auf Genuss 12/13', 'S. 28', NULL, 1),
  (109, 'Lust auf Genuss 12/13', 'S. 31', NULL, 1),
  (110, 'Lust auf Genuss 12/13', 'S. 36', NULL, 1),
  (111, 'Lust auf Genuss 12/13', 'S. 39', NULL, 1),
  (112, 'Lust auf Genuss 12/13', 'S. 58', NULL, 1),
  (113, 'Lust auf Genuss 12/13', 'S. 58', NULL, 1),
  (114, 'Lust auf Genuss 12/13', 'S. 62', NULL, 1),
  (115, 'Beef 18', 'S. 39', NULL, 1),
  (116, 'Beef 18', 'S. 49', NULL, 1),
  (117, 'Beef 18', 'S. 64', NULL, 1),
  (118, 'Kochwerkstatt', 'S. 58', NULL, 2),
  (119, 'Kochwerkstatt', 'S. 197', NULL, 2),
  (120, 'Beef 25', 'S. 34 ff', NULL, 1),
  (121, 'Beef 25', 'S. 96 ff', NULL, 1),
  (122, 'Beef 25', 'S. 146 ff', NULL, 1),
  (123, 'www.br.de','http://www.br.de/fernsehen/bayerisches-fernsehen/sendungen/wir-in-bayern/rezepte/bierzander-birnen-wirsing-gemuese-rezept-stefan-forster-104.html', NULL, 3),
  (124, 'www.spiegel.de','http://www.spiegel.de/panorama/ottolenghis-rezept-langsam-gegarte-lammschulter-mit-pflaumen-und-mandeln-a-975657.html', 'GROSSARTIG!!!', 3),
  (125, 'www.saison.ch','http://www.saison.ch/de/rezepte/fischfilet-mit-orangen-erdnusskruste/detail/', NULL, 3),
  (126, 'sz-magazin.sueddeutsche.de','http://sz-magazin.sueddeutsche.de/texte/anzeigen/43774/Geheimes-Filet', 'Fleisch von Mitte Meer', 3),
  (127, 'Gallische Gelage', 'S. 46', NULL, 2),
  (128, 'Gallische Gelage', 'S. 51', NULL, 2),
  (129, 'Gallische Gelage', 'S. 64', NULL, 2),
  (130, 'Gallische Gelage', 'S. 67', NULL, 2),
  (131, 'Gallische Gelage', 'S. 68', NULL, 2),
  (132, 'Gallische Gelage', 'S. 69', NULL, 2),
  (133, 'Gallische Gelage', 'S. 108', NULL, 2),
  (134, 'Gallische Gelage', 'S. 68 127', NULL, 2),
  (135, 'sz-magazin.sueddeutsche.de','https://sz-magazin.sueddeutsche.de/das-kochquartett/lamm-mit-kreuzkuemmel-und-koriander-83784', NULL, 3),
  (136, 'www.hengstenberg.de','https://www.hengstenberg.de/magazin/feingemacht/Pulled_Pork?utm_source=facebook&utm_medium=cpc&utm_campaign=Pulled_Pork_mit_BBQ_Kraut&utm_content=caro', NULL, 3);

INSERT INTO ingredients (id, name, type) VALUES
  (5, 'Linsen', 'Gemüse'),
  (6, 'Rote Bete', 'Gemüse'),
  (7, 'Erbsen', 'Gemüse'),
  (8, 'Geflügel', 'Fleisch, Geflügel'),
  (9, 'Zitronengras', 'Gemüse'),
  (10, 'Guacamole', 'Salsa, Dip'),
  (11, 'Steinbutt', 'Fisch'),
  (12, 'Kalbsleber', 'Innereine, Kalb'),
  (13, 'Rinderbeinscheibe', 'Fleisch, Rind'),
  (14, 'Wildschwein', 'Fleisch, Wild'),
  (15, 'Kaninchen', 'Fleisch'),
  (16, 'Rehschulter', 'Fleisch, Wild'),
  (17, 'Safran', 'Gewürz'),
  (18, 'Kerbel', 'Kräuter, Gewürz'),
  (19, 'Cocktailsoße', 'Salsa, Dip'),
  (20, 'Chili', 'Gewürz'),
  (21, 'Sesam', 'Trockenfrucht, Samen'),
  (22, 'Rippchen', 'Fleisch'),
  (23, 'Lammhack','Fleisch, Lamm'),
  (24, 'Hähnchen-Tikka', 'Fleisch, Geflügel'),
  (25, 'Rind-Kokos', 'Fleisch, Rind'),
  (26, 'Fleisch', 'Fleisch'),
  (27, 'Hühnerleber', 'Innereine, Geflügel'),
  (28, 'Schinken', 'Fleisch'),
  (29, 'Heringe', 'Fisch'),
  (30, 'Ente', 'Fleisch, Geflügel'),
  (31, 'Feta', 'Käse'),
  (32, 'Lamm', 'Fleisch, Lamm'),
  (33, 'Minze', 'Kräuter, Gewürz'),
  (34, 'Nüsse', 'Trockenfrucht, Samen'),
  (35, 'Kalbsrücken (ausprobiert)', 'Fleisch, Kalb'),
  (36, 'Zwiebeln', 'Gemüse'),
  (37, 'Spare Ribs', 'Fleisch'),
  (38, 'Rosenkohl', 'Gemüse'),
  (39, 'Grünkohl', 'Gemüse'),
  (40, 'Rotkohl / Blaukraut', 'Gemüse'),
  (41, 'Spitzkohl', 'Gemüse'),
  (42, 'Weißkohl', 'Gemüse'),
  (43, 'Brokkoli', 'Gemüse'),
  (44, 'Kürbis', 'Gemüse'),
  (45, 'Laugenstange', 'Gemüse'),
  (46, 'Kartoffeln', 'Gemüse'),
  (47, 'Pumpernickel (ausprobiert)', 'Brot'),
  (48, 'Polenta', 'Getreide'),
  (49, 'Mascarpone', 'Milchprodukt'),
  (50, 'Spinat', 'Gemüse'),
  (51, 'Schweinehaxn', 'Fleisch'),
  (52, 'Rollbraten', 'Fleisch'),
  (53, 'Glasiertes Kassler', 'Fleisch'),
  (54, 'Krustenbraten', 'Fleisch'),
  (55, 'Rinderbrust', 'Fleisch, Rind'),
  (56, 'Schweineschulter', 'Fleisch, Schwein'),
  (57, 'Lachs', 'Fisch'),
  (58, 'Porterhouse-Steak', 'Fleisch, Rind'),
  (59, 'Hochrippe', 'Fleisch'),
  (60, 'Kohlrabi', 'Gemüse'),
  (61, 'Pancetta', NULL),
  (62, 'Gurke', 'Gemüse'),
  (63, 'Thunfisch', NULL),
  (64, 'Bete','Gemüse'),
  (65, 'Mango', NULL),
  (66, 'Williams Christ Birne', NULL),
  (67, 'Pumpernickel Mouse', NULL),
  (68, 'Süßer Gin Tonic', NULL),
  (69, 'Pfirsichsuppe', NULL),
  (70, 'Melonen-Wodka', NULL),
  (71, 'Rum-Passionsfrucht', NULL),
  (72, 'Rind', 'Fleisch, Rind'),
  (73, 'Hummer', NULL),
  (74, 'Gemüse', NULL),
  (75, 'Kalb', 'Fleisch, Kalb'),
  (76, 'Edelfisch', NULL),
  (77, 'Asia', NULL),
  (78, 'Doppelkeule', 'Fleisch'),
  (79, 'Stelzen', NULL),
  (80, 'Keule', 'Fleisch'),
  (81, 'Schulter', 'Fleisch'),
  (82, 'Kronen', 'Fleisch'),
  (83, 'Rinderlende', 'Fleisch, Rind'),
  (84, 'T-Bone-Steak', 'Fleisch, Rind'),
  (85, 'Schinken-Pflaumen', NULL),
  (86, 'Paprikasalat', NULL),
  (87, 'Preiselbeeren', NULL),
  (88, 'Curry', NULL),
  (89, 'Meerrettich', NULL),
  (90, 'Kaffee', NULL),
  (91, 'Schweinebauch mit Schwarte', 'Fleisch, Schwein'),
  (92, 'Reis', NULL),
  (93, 'Kaffeebohnen', NULL),
  (94, 'Äpfel', NULL),
  (95, 'Reiswein', NULL),
  (96, 'Sojasauce', NULL),
  (97, 'Hoisin-Sauce', NULL),
  (98, 'Bohnen-Knoblauch-Püree', NULL),
  (99, 'Tomaten-Oliven-Paste', NULL),
  (100, 'Blauschimmelcreme mit Walnüssen', NULL),
  (101, 'Chorizo', NULL),
  (102, 'Wildsaunacken / Wildschwein', NULL),
  (103, 'Hirschkeule', NULL),
  (104, 'Feldhase', NULL),
  (105, 'Rehkeule', NULL),
  (106, 'Roggensauerteig', NULL),
  (107, 'Schokohopfen', NULL),
  (108, 'Speckfladen', NULL),
  (109, 'Baguette', NULL),
  (110, 'Port-Stilton mit Lamm', NULL),
  (111, 'Zimt-Espresso mit Kaninchen', NULL),
  (112, 'Bier', NULL),
  (113, 'grobkörniger Senf', NULL),
  (114, 'Honig', NULL),
  (115, 'Zutaten für sechs Portionen', NULL),
  (116, '1,7 kg Lammschulter mit Knochen', NULL),
  (117, '25 Knoblauchzehen', NULL),
  (118, 'gehäutet und in einem Stück belassen', NULL),
  (119, '2 Teelöffel Fenchelsamen', NULL),
  (120, '1 Esslöffel ganze Thymianblätter', NULL),
  (121, '2 Teelöffel Paprikapulver', NULL),
  (122, '½ Teelöffel gemahlenes Kurkuma', NULL),
  (123, '1 getrocknete rote Chilischote', NULL),
  (124, '60 g ungesalzene Butter auf Zimmertemperatur', NULL),
  (125, '750 ml trockenen Weißwein', NULL),
  (126, '3 mittelgroße Zwiebeln', NULL),
  (127, 'grob gehackt (360 g Nettogewicht)', NULL),
  (128, '20 Trockenpflaumen', NULL),
  (129, 'entkernt (140 g Nettogewicht)', NULL),
  (130, '3 Esslöffel Olivenöl', NULL),
  (131, '2 Zimtstangen', NULL),
  (132, '3 Lorbeerblätter', NULL),
  (133, '30 g blanchierte weiße Mandeln', NULL),
  (134, 'grob in Stücke von ½ cm Größe gehackt', NULL),
  (135, 'Salz', NULL),
  (136, 'Zubereitung', NULL),
  (137, 'Den Ofen auf 190° C vorheizen (Heißluftherd). Die Haut der Lammschulter 10 Mal mit einem scharfen Messer etwa 1 cm einschneiden und dann mit der Hautseite nach oben in einen großen', NULL),
  (138, 'tiefen Brater legen. Die Maße des Braters sollten etwa 40 cm mal 33 cm betragen. Acht Knoblauchzehen zusammen mit den Fenchelsamen', NULL),
  (139, 'Thymianblättern', NULL),
  (140, 'Paprikapulver', NULL),
  (141, 'Kurkuma', NULL),
  (142, 'Chilischote', NULL),
  (143, '2 Teelöffeln Salz und 50 g Butter mit einem Stabmixer oder in einer Küchenmaschine zerkleinern. Die Paste mit den Händen auf der gesamten Lammschulter verteilen. Beiseite stellen und 30 Minuten bei Zimmertemperatur ruhen lassen.', NULL),
  (144, 'Alle übrigen Zutaten bis auf die Mandeln und die übrige Butter um die Lammschulter herum in den Brater legen. Den Wein dazugießen und genug Wasser hinzufügen', NULL),
  (145, 'damit die Flüssigkeit die Lammschulter zur Hälfte bedeckt. Dazu benötigen Sie etwa 750 ml Wasser.', NULL),
  (146, 'Ein Stück feuchtes', NULL),
  (147, 'fettdichtes Brotpapier direkt über die Lammschulter und die Flüssigkeit legen', NULL),
  (148, 'den Bräter mit zwei leicht aufgelegten Schichten Alufolie abdecken und 60 Minuten in den Ofen stellen. Die Temperatur auf 150° C reduzieren und weitere 5 Stunden braten lassen', NULL),
  (149, 'bis das Lammfleisch sich vom Knochen löst. Dabei ab und zu das Fett abschöpfen und bei Bedarf mehr Wasser dazugeben - falls die Flüssigkeit zu stark verdampft. Das Lamm aus dem Ofen nehmen', NULL),
  (150, 'auf ein separates Backblech legen und bis zum Servieren warm aufbewahren.', NULL),
  (151, 'Die übrige Butter in einer kleinen Pfanne zergehen lassen und die Mandeln hinzufügen. Bei mittlerer Hitze 4 bis 5 Minuten umrühren', NULL),
  (152, 'damit die Mandeln mit Butter umhüllt und geröstet werden. Vom Herd nehmen und ebenfalls beiseite stellen.', NULL),
  (153, 'Die Lorbeerblätter und Zimtstangen aus dem Saft entfernen und diesen dann in eine mittelgroße Pfanne geben: Sie sollten jetzt ungefähr 500 ml Saft haben. Auf starker Flamme schnell zum Kochen bringen und 2 Minuten kochen lassen', NULL),
  (154, 'bis 1/3 der Soße verdampft ist. Eventuell an der Oberfläche abgelagertes Fett entfernen.', NULL),
  (155, 'Das Lamm zum Servieren auf die Teller verteilen und die Soße drübergießen. Mit den Mandeln bestreuen und sofort servieren.', NULL),
  (156, 'Ergibt  Portionen', NULL),
  (157, '4	Kabeljau-Rückenfilets à ca. 200 g', NULL),
  (158, '1 EL	Zitronensaft', NULL),
  (159, 'Pfeffer', NULL),
  (160, '2	Bio-Orangen', NULL),
  (161, '150 g	geröstete', NULL),
  (162, 'gesalzene Erdnüsse', NULL),
  (163, '4 EL	Wasser', NULL),
  (164, '4 EL	Olivenöl', NULL),
  (165, '3 TL	Honig', NULL),
  (166, '0.5 Bund	Thymian', NULL),
  (167, '1 dl	Weisswein', NULL),
  (168, '1 TL	Maisstärke', NULL),
  (169, 'Für 4-6 Personen: 800-1000 g Secreto vom Iberico-Schwein (das sind zwei Stücke)', NULL),
  (170, '1 Knoblauchzehe', NULL),
  (171, '1 Rosmarinzweig', NULL),
  (172, '1 TL Pimentsamen oder Wacholderbeeren', NULL),
  (173, '2 EL Olivenöl', NULL),
  (174, 'Secreto 2 h vor dem Essen aus dem Kühlschrank nehmen', NULL),
  (175, 'in eine Schale legen. Die Gewürze hacken', NULL),
  (176, 'mit 2 EL Olivenöl mischen', NULL),
  (177, 'das Fleisch damit einreiben.', NULL),
  (178, 'Das Fleisch mit Salz und Pfeffer würzen und bei großer Hitze von beiden Seiten je etwa 4 Min. grillen. Auf einem warmen Teller ein paar Minuten ruhen lassen.', NULL),
  (179, 'Champignons', NULL),
  (180, 'Hähnchenbrustfilets', NULL),
  (181, 'Schweinefleisch mit Knochen', NULL),
  (182, 'Lammkeule ca. 2 1/2 kg', NULL),
  (183, '1 1/2 kg Rinderschmorbraten', NULL),
  (184, 'Für 4 Personen', NULL),
  (185, '600 g Lammkeule (ausgelöst und in Streifen geschnitten wie für Geschnetzeltes)', NULL),
  (186, '50 ml Sojasauce (dunkel oder Tamari-Sojasauce)', NULL),
  (187, '30 ml Sesamöl', NULL),
  (188, '20 g Ingwer (fein gehackt)', NULL),
  (189, '3 EL Kreuzkümmel (geröstet und leicht gemörsert)', NULL),
  (190, '1 EL Koriandersamen (geröstet und gemörsert)', NULL),
  (191, '50 ml neutrales Öl zum Braten (etwa Sonnenblume)', NULL),
  (192, '4 Schalotten (in Streifen oder Ringe geschnitten)', NULL),
  (193, '1 Knoblauchzehe (gehackt)', NULL),
  (194, '1 Bund frischer Koriander', NULL),
  (195, 'einige Blätter Minze', NULL),
  (196, 'Die Lammstreifen mindestens 2 Stunden in dunkler Sojasauce mit Sesamöl und Ingwer marinieren. Kurz vor dem Anbraten Kreuzkümmel und Koriandersamen zum Fleisch geben und gut durchmengen. In einer Pfanne das Sonnenblumenöl erhitzen und die Lammstreifen unter Schwenken scharf anbraten. Fleisch aus der Pfanne nehmen und die Schalotten mit dem Knoblauch darin anschwitzen. Lammfleisch wieder zufügen', NULL),
  (197, 'mit dem geschnittenen Koriander und der Minze vermengen und servieren. Nötigenfalls mit Salz und schwarzem Pfeffer nochmals abschmecken.', NULL),
  (198, 'Zutaten für 4 Portionen', NULL),
  (199, '1-2 kg Schweinenacken oder Schweineschulter mit Knochen (wenn Sie es noch saftiger wollen)', NULL),
  (200, 'Trockengewürz zum Einreiben:', NULL),
  (201, '3 EL Salz', NULL),
  (202, '3 EL brauner Zucker', NULL),
  (203, '2 EL Kümmel', NULL),
  (204, '2 EL Rosmarin', NULL),
  (205, '1 EL Senfkörner', NULL),
  (206, '1 EL Paprika', NULL),
  (207, '1 EL Knoblauchpulver', NULL),
  (208, '1 EL Zwiebelpulver', NULL),
  (209, '1 EL Curry', NULL),
  (210, '1 EL Cayenne-Pfeffer', NULL),
  (211, '1/2 Tube Hengstenberg Delikatess-Senf Mittelscharf', NULL),
  (212, '1 Beutel Hengstenberg BBQ Kraut by Mildessa', NULL),
  (213, '1 Flasche Hengstenberg Milder Apfel Balsamessig', NULL),
  (214, 'Gemüsebrühe (im Verhältnis 1:1 zum Apfelessig)', NULL),
  (215, 'Zubereitungszeit: ca. 60 Minuten', NULL),
  (216, 'Schritt 1: Die Vorberitung', NULL),
  (217, 'Für die Gewürzkruste des Fleischs- im Grilljargon heißt es „Trocken-Rub” - rösten Sie alle Gewürze in einer beschichteten Pfanne 2 Minuten leicht an. Falls notwendig', NULL),
  (218, 'zermörsern Sie die Masse anschließend nochmal.', NULL),
  (219, 'Schritt 2: Das Fleisch vorbereiten', NULL),
  (220, 'Waschen Sie das Fleisch', NULL),
  (221, 'tupfen es trocken und schneiden Sie weißes Fett und die Silberhaut grob ab. Dann reiben Sie das Fleisch großzügig mit Senf und anschließend mit dem Rub ein. Wickeln Sie das marinierte Fleisch in Frischhaltefolie und legen es 12 Stunden in den Kühlschrank.', NULL),
  (222, 'Schritt 3: Das Fleisch garen', NULL),
  (223, 'Heizen Sie den Ofen auf 110 °C vor - falls möglich', NULL),
  (224, 'kombinieren Sie Ober- und Unterhitze mit Umluft', NULL),
  (225, 'ansonsten nutzen Sie nur Umlufthitze. Geben Sie die Brühe und  den Apfel Balsamessig in einen Bräter oder eine feuerfeste Schale. Der Apfel Balsamessig verdampft während des Garens nach und nach und gibt dem Fleisch später ein besonderes Aroma. Wichtig: Stechen Sie ein Thermometer mittig in das Fleisch', NULL),
  (226, 'bevor Sie es in den Bräter legen', NULL),
  (227, 'denn oft sind die Temperaturanzeigen am Ofen ungenau. Wenn das Fleisch für die Gäste am Abend fertig sein soll', NULL),
  (228, 'müssen Sie früh aufstehen: Bei 2 kg Fleisch beträgt die Garzeit circa 11 Stunden.', NULL),
  (229, 'Schritt 4: Das Fleisch pullen', NULL),
  (230, 'Bei 92 °C Kerntemperatur ist Ihr Fleisch fertig. Lassen Sie es nun noch etwa eine halbe Stunde in Alufolie ruhen - oder auch länger', NULL),
  (231, 'wenn Ihre Gäste sich verspäten. Dann können Sie es sogar noch gut in Folie und Handtüchern eingepackt ins Bett legen und dort ruhen lassen. Wenn Sie Lust haben', NULL),
  (232, 'pullen Sie das Fleisch später vor den Augen Ihrer Gäste - sie werden beeindruckt sein.', NULL);

INSERT INTO recipe_ingredients (recipe_id, ingredient_id, amount, unit) VALUES
  (3, 5, NULL, NULL),
  (3, 6, NULL, NULL),
  (3, 7, NULL, NULL),
  (4, 5, NULL, NULL),
  (4, 6, NULL, NULL),
  (4, 8, NULL, NULL),
  (4, 9, NULL, NULL),
  (4, 10, NULL, NULL),
  (5, 11, NULL, NULL),
  (5, 12, NULL, NULL),
  (5, 13, NULL, NULL),
  (5, 14, NULL, NULL),
  (5, 15, NULL, NULL),
  (5, 16, NULL, NULL),
  (7, 9, NULL, NULL),
  (7, 17, NULL, NULL),
  (7, 18, NULL, NULL),
  (7, 19, NULL, NULL),
  (7, 20, NULL, NULL),
  (7, 21, NULL, NULL),
  (8, 22, NULL, NULL),
  (8, 23, NULL, NULL),
  (8, 24, NULL, NULL),
  (8, 25, NULL, NULL),
  (14, 26, NULL, NULL),
  (20, 27, NULL, NULL),
  (20, 28, NULL, NULL),
  (20, 29, NULL, NULL),
  (21, 30, NULL, NULL),
  (21, 31, NULL, NULL),
  (21, 32, NULL, NULL),
  (21, 33, NULL, NULL),
  (21, 5, NULL, NULL),
  (21, 6, NULL, NULL),
  (21, 34, NULL, NULL),
  (22, 30, NULL, NULL),
  (22, 35, NULL, NULL),
  (22, 36, NULL, NULL),
  (22, 37, NULL, NULL),
  (23, 38, NULL, NULL),
  (23, 39, NULL, NULL),
  (23, 40, NULL, NULL),
  (23, 41, NULL, NULL),
  (23, 42, NULL, NULL),
  (23, 43, NULL, NULL),
  (26, 44, NULL, NULL),
  (26, 45, NULL, NULL),
  (26, 46, NULL, NULL),
  (26, 47, NULL, NULL),
  (26, 48, NULL, NULL),
  (26, 49, NULL, NULL),
  (26, 50, NULL, NULL),
  (27, 51, NULL, NULL),
  (27, 52, NULL, NULL),
  (27, 53, NULL, NULL),
  (27, 54, NULL, NULL),
  (28, 22, NULL, NULL),
  (28, 55, NULL, NULL),
  (28, 56, NULL, NULL),
  (28, 57, NULL, NULL),
  (28, 58, NULL, NULL),
  (28, 59, NULL, NULL),
  (29, 60, NULL, NULL),
  (29, 61, NULL, NULL),
  (29, 36, NULL, NULL),
  (29, 62, NULL, NULL),
  (29, 63, NULL, NULL),
  (29, 64, NULL, NULL),
  (29, 65, NULL, NULL),
  (31, 66, NULL, NULL),
  (31, 67, NULL, NULL),
  (31, 68, NULL, NULL),
  (31, 69, NULL, NULL),
  (31, 70, NULL, NULL),
  (31, 71, NULL, NULL),
  (32, 30, NULL, NULL),
  (32, 72, NULL, NULL),
  (32, 73, NULL, NULL),
  (32, 74, NULL, NULL),
  (32, 75, NULL, NULL),
  (32, 76, NULL, NULL),
  (32, 77, NULL, NULL),
  (33, 78, NULL, NULL),
  (33, 79, NULL, NULL),
  (33, 80, NULL, NULL),
  (33, 81, NULL, NULL),
  (33, 82, NULL, NULL),
  (35, 83, NULL, NULL),
  (35, 84, NULL, NULL),
  (35, 85, NULL, NULL),
  (35, 86, NULL, NULL),
  (36, 20, NULL, NULL),
  (36, 87, NULL, NULL),
  (36, 88, NULL, NULL),
  (36, 89, NULL, NULL),
  (36, 90, NULL, NULL),
  (59, 6, NULL, NULL),
  (62, 91, NULL, NULL),
  (64, 92, NULL, NULL),
  (64, 17, NULL, NULL),
  (91, 93, NULL, NULL),
  (94, 94, NULL, NULL),
  (96, 95, NULL, NULL),
  (96, 96, NULL, NULL),
  (96, 97, NULL, NULL),
  (106, 98, NULL, NULL),
  (106, 99, NULL, NULL),
  (106, 100, NULL, NULL),
  (118, 101, NULL, NULL),
  (120, 102, NULL, NULL),
  (120, 103, NULL, NULL),
  (120, 104, NULL, NULL),
  (120, 105, NULL, NULL),
  (121, 106, NULL, NULL),
  (121, 107, NULL, NULL),
  (121, 108, NULL, NULL),
  (121, 109, NULL, NULL),
  (122, 110, NULL, NULL),
  (122, 111, NULL, NULL),
  (123, 112, NULL, NULL),
  (123, 113, NULL, NULL),
  (123, 114, NULL, NULL),
  (124, 115, NULL, NULL),
  (124, 116, NULL, NULL),
  (124, 117, NULL, NULL),
  (124, 118, NULL, NULL),
  (124, 119, NULL, NULL),
  (124, 120, NULL, NULL),
  (124, 121, NULL, NULL),
  (124, 122, NULL, NULL),
  (124, 123, NULL, NULL),
  (124, 124, NULL, NULL),
  (124, 125, NULL, NULL),
  (124, 126, NULL, NULL),
  (124, 127, NULL, NULL),
  (124, 128, NULL, NULL),
  (124, 129, NULL, NULL),
  (124, 130, NULL, NULL),
  (124, 131, NULL, NULL),
  (124, 132, NULL, NULL),
  (124, 133, NULL, NULL),
  (124, 134, NULL, NULL),
  (124, 135, NULL, NULL),
  (124, 136, NULL, NULL),
  (124, 137, NULL, NULL),
  (124, 138, NULL, NULL),
  (124, 139, NULL, NULL),
  (124, 140, NULL, NULL),
  (124, 141, NULL, NULL),
  (124, 142, NULL, NULL),
  (124, 143, NULL, NULL),
  (124, 144, NULL, NULL),
  (124, 145, NULL, NULL),
  (124, 146, NULL, NULL),
  (124, 147, NULL, NULL),
  (124, 148, NULL, NULL),
  (124, 149, NULL, NULL),
  (124, 150, NULL, NULL),
  (124, 151, NULL, NULL),
  (124, 152, NULL, NULL),
  (124, 153, NULL, NULL),
  (124, 154, NULL, NULL),
  (124, 155, NULL, NULL),
  (125, 156, NULL, NULL),
  (125, 157, NULL, NULL),
  (125, 158, NULL, NULL),
  (125, 135, NULL, NULL),
  (125, 159, NULL, NULL),
  (125, 160, NULL, NULL),
  (125, 161, NULL, NULL),
  (125, 162, NULL, NULL),
  (125, 163, NULL, NULL),
  (125, 164, NULL, NULL),
  (125, 165, NULL, NULL),
  (125, 166, NULL, NULL),
  (125, 167, NULL, NULL),
  (125, 168, NULL, NULL),
  (126, 169, NULL, NULL),
  (126, 170, NULL, NULL),
  (126, 171, NULL, NULL),
  (126, 172, NULL, NULL),
  (126, 173, NULL, NULL),
  (126, 174, NULL, NULL),
  (126, 175, NULL, NULL),
  (126, 176, NULL, NULL),
  (126, 177, NULL, NULL),
  (126, 178, NULL, NULL),
  (127, 179, NULL, NULL),
  (127, 94, NULL, NULL),
  (128, 94, NULL, NULL),
  (129, 180, NULL, NULL),
  (130, 181, NULL, NULL),
  (132, 182, NULL, NULL),
  (133, 183, NULL, NULL),
  (135, 184, NULL, NULL),
  (135, 185, NULL, NULL),
  (135, 186, NULL, NULL),
  (135, 187, NULL, NULL),
  (135, 188, NULL, NULL),
  (135, 189, NULL, NULL),
  (135, 190, NULL, NULL),
  (135, 191, NULL, NULL),
  (135, 192, NULL, NULL),
  (135, 193, NULL, NULL),
  (135, 194, NULL, NULL),
  (135, 195, NULL, NULL),
  (135, 135, NULL, NULL),
  (135, 159, NULL, NULL),
  (135, 196, NULL, NULL),
  (135, 197, NULL, NULL),
  (136, 198, NULL, NULL),
  (136, 199, NULL, NULL),
  (136, 200, NULL, NULL),
  (136, 201, NULL, NULL),
  (136, 202, NULL, NULL),
  (136, 203, NULL, NULL),
  (136, 204, NULL, NULL),
  (136, 205, NULL, NULL),
  (136, 206, NULL, NULL),
  (136, 207, NULL, NULL),
  (136, 208, NULL, NULL),
  (136, 209, NULL, NULL),
  (136, 210, NULL, NULL),
  (136, 211, NULL, NULL),
  (136, 212, NULL, NULL),
  (136, 213, NULL, NULL),
  (136, 214, NULL, NULL),
  (136, 109, NULL, NULL),
  (136, 215, NULL, NULL),
  (136, 216, NULL, NULL),
  (136, 217, NULL, NULL),
  (136, 218, NULL, NULL),
  (136, 219, NULL, NULL),
  (136, 220, NULL, NULL),
  (136, 221, NULL, NULL),
  (136, 222, NULL, NULL),
  (136, 223, NULL, NULL),
  (136, 224, NULL, NULL),
  (136, 225, NULL, NULL),
  (136, 226, NULL, NULL),
  (136, 227, NULL, NULL),
  (136, 228, NULL, NULL),
  (136, 229, NULL, NULL),
  (136, 230, NULL, NULL),
  (136, 231, NULL, NULL),
  (136, 232, NULL, NULL);
